# Usa la imagen oficial de Nginx, un servidor web ligero y eficiente.
FROM nginx:alpine

# Copia todos los archivos de tu proyecto (HTML, CSS, JS, img) a la carpeta pública del servidor.
COPY . /usr/share/nginx/html